[package]
name = "gearsx"
version = "0.1.0"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
diesel = { version = "1.4.0", features = ["postgres", "uuidv07"] }
dotenv = "0.10"
uuid = "0.7"
